version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    reviewers:
      - "ushibutatory"
