name: Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - .github/workflows/deploy-prod.yaml
      - src/**
      - data/**.yaml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "17"
      - name: Test
        run: |
          cd "${GITHUB_WORKSPACE}/src/app"
          npm install
          npm run lint
          npm run test
      - name: Generate Calendar
        run: |
          cd "${GITHUB_WORKSPACE}/src/app"
          npm run generate
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: calendars
          path: src/app/dist/*
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_BUCKET_NAME: s3://umamusume-birthdays/
          DISTS: src/app/dist
        run: |
          aws s3 cp ${DISTS} ${AWS_BUCKET_NAME} --recursive
