name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-prod.yaml
      - src/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Test
        run: |
          cd "${GITHUB_WORKSPACE}/src"
          npm install
          npm run lint
          npm run test
      - name: Create Calendar
        run: |
          cd "${GITHUB_WORKSPACE}/src"
          npm run execute
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: calendars
          path: src/dist/*
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_BUCKET_NAME: s3://umamusume-birthdays/
          DISTS: src/dist
        run: |
          aws s3 cp ${DISTS} ${AWS_BUCKET_NAME} --recursive
