name: Update Calendar

on:
  push:
    branches:
      - "develop"
    paths:
      - .github/workflows/deploy.yaml
      - apps/generator/**

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Create Calendar
        run: |
          npm install
          npm run execute
        working-directory: "./apps/generator"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: calendars
          path: ./apps/generator/dist/*
      - name: Update dist directory
        run: |
          cp apps/generator/dist/* docs/dist -r -u
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git add docs/dist/*
          git commit -m "update: iCal files"
          git push
