name: Validate

on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - .github/workflows/**.yaml
      - src/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Test
        run: |
          cd "${GITHUB_WORKSPACE}/src"
          npm install
          npm run lint
          npm run test
      - name: Create Calendar
        run: |
          cd "${GITHUB_WORKSPACE}/src"
          npm run execute
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: calendars
          path: src/dist/*
