name: Validate

on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - .github/workflows/**.yaml
      - apps/generator/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Test
        run: |
          npm install
          npm run lint
          npm run test
        working-directory: "./apps/generator"
      - name: Create Calendar
        run: |
          npm run execute
        working-directory: "./apps/generator"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calendars
          path: ./apps/generatordist/*
